poznajmy_polskie_zabytki/__init__.py
import os

from flask import Flask
from flask import jsonify

__all__ = ["db", "create_app"]


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True, template_folder="templates")
    app.config.from_mapping(
        SECRET_KEY="dev",
        DATABASE=os.path.join(app.instance_path, 'zabytki.sqlite'),
        INPUT=os.path.join(app.instance_path, 'DANE_ZESTWIENIE_ZRN.csv'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile("config.py", silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route("/hello")
    def hello_b():
        return jsonify("Hello, World (json)!")

    from . import db
    db.init_app(app)

    from . import views
    app.register_blueprint(views.bp)

    return app

poznajmy_polskie_zabytki/views.py
from poznajmy_polskie_zabytki.db import get_db
from poznajmy_polskie_zabytki.db import close_db

import sqlite3
from flask import Blueprint
from flask import render_template
from flask import request
from flask import abort


bp = Blueprint("views", __name__)


def _create_sql_query(*, city="", parish="", county="", keyword="", voivodeship="") -> str:
    if city or parish or county or keyword or voivodeship:
        sql_query = "SELECT * from zabytki where"
    else:
        return ""
    if city:
        sql_query += " miejscowosc='" + city + "'"
    if parish:
        if city:
            sql_query += " and"
        sql_query += " gmina like '%" + parish + "%'"
    if county:
        if city or parish:
            sql_query += " and"
        sql_query += " powiat='" + county + "'"
    if voivodeship:
        if city or parish or county:
            sql_query += " and"
        sql_query += " wojewodztwo='" + voivodeship + "'"
    if keyword:
        if city or parish or county:
            sql_query += " and"
        sql_query += " ( nazwa like '%" + keyword + "%'" + " or funkcja like '%" + keyword + "%'" \
                     " or wojewodztwo like '%" + keyword + "%'" + " or chronologia like '%" + keyword + "%'" \
                     " or ulica like '%" + keyword + "%' )"

    sql_query += " order by powiat, gmina, miejscowosc, ulica"
    return sql_query


def _get_query_params(r):
    city = r.args.get("miasto", "").replace("'", "")
    parish = r.args.get("gmina", "").replace("'", "")
    county = r.args.get("powiat", "").replace("'", "")
    voivodeship = r.args.get("wojewodztwo", "").replace("'", "")
    keyword = request.args.get("dowolneslowo", "").replace("'", "")
    return city, parish, county, keyword, voivodeship


def _generate_trip(monuments=None):
    pass


def _generate_pdf_report(monuments=None):
    pass


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/wyszukaj/')
def wyszukaj():
    city, parish, county, keyword, voivodeship = _get_query_params(request)
    if any([city, parish, county, keyword]):
        params = [": ".join(x) for x in
                  [["miasto", city], ["gmina", parish], ["powiat", county], ["wojewodztwo", voivodeship]] if x[1]]
        try:
            db = get_db()
        except sqlite3.Error:
            abort(500)
        else:
            sql_query = _create_sql_query(city=city, parish=parish, county=county, keyword=keyword)
            output = db.execute(sql_query).fetchall()
            items = [tuple([id_temp+1]) + tuple(item) for id_temp, item in enumerate(output)]
        finally:
            close_db()
        return render_template("search.html", city=city, params=params, items=items, quantity=len(items))
    else:
        return render_template('search_main.html')


@bp.route('/wygeneruj/')
def wygeneruj():
    city, parish, county, keyword, voivodeship = _get_query_params(request)
    if any([city, parish, county, voivodeship]):
        params = [": ".join(x) for x in
                  [["miasto", city], ["gmina", parish], ["powiat", county], ["wojewodztwo", voivodeship]] if x[1]]
        try:
            db = get_db()
        except sqlite3.Error:
            abort(500)
        else:
            sql_query = _create_sql_query(city=city, parish=parish, county=county, voivodeship=voivodeship)
            output = db.execute(sql_query).fetchall()
            items = [tuple(item) for item in output]
            trip_msg1 = " !!! Wycieczka nie może być wygenerowana (funcjonalność nie jest zaimplementowana)."
            trip_msg2 = "Aczkolwiek zostało znalezionch " + str(len(items)) + " potencjalnych zabytków. !!!"
        finally:
            close_db()

        return render_template("generate.html", params=params, trip1=trip_msg1, trip2=trip_msg2)

    return render_template('generate_main.html')

poznajmy_polskie_zabytki/templates/base.html
<!doctype html>
<html style="height:100%">

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{% block title %}{% endblock %} - Poznajmy polskie zabytki</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>

<nav>
  <h2><a href="{{ url_for('views.index') }}">Poznajmy polskie zabytki</a></h2>
</nav>

<body style="height:100%">
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block header_ext %}{% endblock %}
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>
</body>

</html>

poznajmy_polskie_zabytki/templates/generate.html
{% extends 'base.html' %}

{% block header_ext %}
Dla zadanych parametrów wyszukiwania:
    {% for param in params %}
<br>
        -- {{ param }}
    {% endfor %}

<p>Proponujemy Ci następującą wycieczkę:</p>

{% endblock %}

{% block content %}
    {% for item in items %}
        <p>{{ item }}</p>
    {% endfor %}
<p style="background-color:powderblue;"><i><b> {{ trip1 }} </b></i></p>
<p style="background-color:powderblue;"><i><b> {{ trip2 }} </b></i></p>
{% endblock %}

poznajmy_polskie_zabytki/templates/generate_main.html
{% extends 'base.html' %}


{% block header %}
<p>Super:) Wygenerujemy zaraz wycieczkę (i poznamy polskie zabytki).</p>
{% endblock %}

{% block content %}
	<form action="/wygeneruj/" method="get">
        <br>
        <p>Generator wycieczek:</p>
        <span>
            <input type="text" name="miasto" placeholder="..wpisz miejscowość.." autocomplete="off"/>
            <input type="text" name="gmina" placeholder="..wpisz gminę.." autocomplete="off"/>
            <input type="text" name="powiat" placeholder="..wpisz powiat.." autocomplete="off"/>
            <input type="text" name="wojewodztwo" placeholder="..wpisz wojewodztwo.." autocomplete="on"/>
        </span>
        <br/>
        <input type="submit" value="Generuj"/>
    </form>
{% endblock %}

poznajmy_polskie_zabytki/templates/index.html
{% extends 'base.html' %}


{% block header %}
<p>Fajnie, że jesteś:) To może poznajmy razem polskie zabytki?</p>
{% endblock %}

{% block content %}
<br>
<p>Dzięki tej stronie możesz:</p>
<ul>
  <li>
  wyszukać zabytki w Twojej okolicy:
  <br>
  <a href="/wyszukaj">Wyszukaj zabytki</a>
  <br>
  </li>
  <li>
  wygenerować losową wycieczkę po okolicznych zabytkach:
  <br>
  <a href="/wygeneruj">Wygeneruj wycieczkę</a>
  </li>
</ul>
{% endblock %}

poznajmy_polskie_zabytki/templates/search.html
{% extends 'base.html' %}

{% block header_ext %}
Parametry wyszukiwania:
    {% for param in params %}
<br>
        -- {{ param }}
    {% endfor %}
<br>
<p>Liczba znalezionych zabytków wynosi: <b>{{ quantity }}</b>.</p>

{% endblock %}

{% block content %}
<table style="width:100%">
  <tr>
    <th>Id</th>
    <th>Nazwa zabytku</th>
    <th>Chronologia</th>
    <th>Funkcja</th>
    <th>Wojewodztwo</th>
    <th>Powiat</th>
    <th>Gmina</th>
    <th>Miejscowość</th>
    <th>Ulica/Nr</th>
  </tr>
    {% for item in items %}
      <tr>
          <td>{{ item[0] }}</td>
          <td>{{ item[5] }}</td>
          {% if item[6] %}
          <td>{{ item[6] }}</td>
          {% else %}
          <td>-</td>
          {% endif %}
          <td>{{ item[7] }}</td>
          <td>{{ item[10] }}</td>
          <td>{{ item[11] }}</td>
          <td>{{ item[12] }}</td>
          <td>{{ item[13] }}</td>
          {% if item[14] %}
          <td>{{ item[14] }} {{ item[15] }}</td>
          {% else %}
          <td>-</td>
          {% endif %}
      </tr>
    {% endfor %}
</table>
{% endblock %}

poznajmy_polskie_zabytki/templates/search_main.html
{% extends 'base.html' %}


{% block header %}
<p>Super:) Poznajemy razem polskie zabytki.</p>
{% endblock %}

{% block content %}
	<form action="/wyszukaj/" method="get">
        <br>
        <p>Wyszukiwarka zabytków:</p>
        <span>
            <input type="text" name="miasto" placeholder="..wpisz miejscowość.." autocomplete="off"/>
            <input type="text" name="gmina" placeholder="..wpisz gminę.." autocomplete="off"/>
            <input type="text" name="powiat" placeholder="..wpisz powiat.." autocomplete="off"/>
            <input type="text" name="dowolneslowo" placeholder="..wpisz inne słowo kluczowe.." autocomplete="off"/>
        </span>
        <br/>
        <input type="submit" value="Szukaj"/>
    </form>
{% endblock %}